### ISSUE TITLE
[Bug] pacifica-policy-cmd searchsync

### ISSUE THREAD

**Issue by GitBytes** [pacifica/pacifica-policy#75]
### Pacifica Policy version
`v0.6.0`

### Pacifica Core Software versions
`pacifica-metadata==0.10.0`

### Platform Details
el7

### Scenario:
Sync pgsql to new es index with admin tools per docs

### Output:
```
Starting values (updatedException in thread Thread-1:
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/opt/rh/python27/root/usr/lib64/python2.7/threading.py", line 757, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/search_sync/lib/python2.7/site-packages/pacifica/policy/search_sync.py", line 161, in start_work
    try_doing_work(cli, job)
  File "/opt/search_sync/lib/python2.7/site-packages/pacifica/policy/search_sync.py", line 174, in try_doing_work
    helpers.bulk(cli, yield_data(*job))
  File "/opt/search_sync/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 257, in bulk
    for ok, item in streaming_bulk(client, actions, *args, **kwargs):
  File "/opt/search_sync/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 180, in streaming_bulk
    client.transport.serializer):
  File "/opt/search_sync/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 58, in _chunk_actions
    for action, data in actions:
  File "/opt/search_sync/lib/python2.7/site-packages/pacifica/policy/search_render.py", line 31, in generate
    'doc': render_cls.render(obj, True, obj_cls != 'transactions'),
  File "/opt/search_sync/lib/python2.7/site-packages/pacifica/policy/search/base.py", line 83, in render
    ret[key] = getattr(cls, key)(**obj)
  File "/opt/search_sync/lib/python2.7/site-packages/pacifica/policy/search/transactions.py", line 65, in access_url
    return get_config().get('policy', 'release_url_format').format(**trans_obj)
KeyError: 'transaction'
```

**Comment by dmlb2000** [comment]
This is a documentation issue...

The transaction object referenced in the stack trace is the JSON object directly from the metadata API. The transaction key isn't part of the transaction object, just the `_id` is.

The examples in https://github.com/pacifica/pacifica-policy/blob/9ac227ba47666f8cba073b6feebf0b1f6d50ab1c/pacifica/policy/config.py#L24 changed that reference but the docs didn't get updated.

**Comment by GitBytes** [comment]
@dmlb2000 Do you have any additional advice on how we should be addressing our sync command as it changed from metadata to policy? I am having a hard time seeing the connection between what the bug was as described and the documentation that was put forth as the fix. In short, how should we be invoking the es sync/create mechanism differently such that the index can be regenerated as expected? By changing the docs, is it possibly the case as you see it that we may be missing a piece of configuration to support this function of the pacifica-policy-cmd tool? Further clarification may be required or insight provided. Thanks.

**Comment by dmlb2000** [comment]
@GitBytes Yes, checkout your policy configuration file. Then look in the `[policy]` section and look for the `release_url_format` key. The value probably has a format specifier (something surrounded by `{}`) that references `transaction`. That should be changed to `_id`.
